# Generated by Django 4.2.3 on 2023-07-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=250, null=True)),
                ('outputFolder', models.TextField()),
            ],
        ),
    ]
